services:
  # Redis for state management and caching
  redis:
    image: redis:7-alpine
    container_name: sapiens-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sapiens-network

  # Sapiens Engine API (Minimal)
  api:
    image: ghcr.io/whitetrafficlight/sapiensengine:backend-latest
    container_name: sapiens-api
    restart: unless-stopped
    # 포트를 내부로만 노출 (nginx를 통해서만 접근)
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - DOMAIN=${DOMAIN}
      - NEXTJS_SERVER_URL=${NEXTJS_SERVER_URL}
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - sapiens-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (HTTPS 지원)
  nginx:
    image: nginx:alpine
    container_name: sapiens-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - api
    networks:
      - sapiens-network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: sapiens-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL:-admin@agoramind.net} -d agoramind.net -d www.agoramind.net --agree-tos
    networks:
      - sapiens-network

volumes:
  redis_data:

networks:
  sapiens-network:
    driver: bridge 