name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, backend-deploy-clean ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Alternative: Use Docker Hub if GHCR fails
  # REGISTRY: docker.io
  # IMAGE_NAME: whitetrafficlight/sapiens-engine

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      continue-on-error: true

    - name: Initialize submodules safely
      run: |
        git submodule update --init --recursive || echo "Submodule update failed, continuing..."
        git submodule status || echo "Submodule status check failed, continuing..."

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Run tests
      run: |
        # Add your test commands here
        # pytest tests/ -v
        echo "Tests would run here"

    - name: Lint code
      run: |
        pip install flake8 black
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # black --check .
        echo "Linting would run here"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/backend-deploy-clean'
    
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      continue-on-error: true

    - name: Initialize submodules safely
      run: |
        git submodule update --init --recursive || echo "Submodule update failed, continuing..."
        git submodule status || echo "Submodule status check failed, continuing..."

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Convert repository name to lowercase
      id: lowercase
      run: echo "IMAGE_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Fallback login to Docker Hub (if GHCR fails)
      if: failure()
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.IMAGE_NAME_LOWER }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=backend-latest,enable=${{ github.ref == 'refs/heads/backend-deploy-clean' }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend-deploy-clean'
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      continue-on-error: true

    - name: Initialize submodules safely
      run: |
        git submodule update --init --recursive || echo "Submodule update failed, continuing..."
        git submodule status || echo "Submodule status check failed, continuing..."

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        port: ${{ secrets.PRODUCTION_PORT || 22 }}
        script: |
          # Navigate to application directory
          cd /opt/sapiens-engine
          
          # Pull latest code from backend branch
          git fetch origin
          git checkout backend-deploy-clean
          git pull origin backend-deploy-clean
          
          # Create environment file from secrets
          cat > .env << EOF
          ENVIRONMENT=production
          DOMAIN=${{ secrets.DOMAIN }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
          NEXTJS_SERVER_URL=https://${{ secrets.DOMAIN }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_URL=redis://redis:6379
          EOF
          
          # Login to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull latest image
          docker-compose -f docker-compose-minimal.yml pull
          
          # Deploy with zero-downtime
          docker-compose -f docker-compose-minimal.yml up -d --remove-orphans
          
          # Clean up old images
          docker image prune -f
          
          # Wait for containers to be ready
          echo "⏳ Waiting for containers to start..."
          sleep 45
          
          # Check Docker container health
          echo "🔍 Checking container status..."
          docker-compose -f docker-compose-minimal.yml ps
          
          # Robust health check with retries
          echo "🏥 Running health check..."
          for i in {1..10}; do
            echo "Attempt $i/10..."
            
            # First check if nginx is responding
            if curl -f --connect-timeout 10 --max-time 30 http://localhost/health 2>/dev/null; then
              echo "✅ HTTP health check passed"
              break
            elif curl -f --connect-timeout 10 --max-time 30 https://${{ secrets.DOMAIN }}/health 2>/dev/null; then
              echo "✅ HTTPS health check passed"
              break
            else
              echo "❌ Health check failed (attempt $i/10)"
              if [ $i -eq 10 ]; then
                echo "🚨 Health check failed after 10 attempts"
                echo "📋 Container logs:"
                docker-compose -f docker-compose-minimal.yml logs --tail=20 api
                docker-compose -f docker-compose-minimal.yml logs --tail=20 nginx
                exit 1
              fi
              sleep 15
            fi
          done
          
          echo "🎉 Deployment successful!"

  notify:
    needs: [test, build, deploy]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Notify Slack on success
      if: needs.deploy.result == 'success' && vars.SLACK_WEBHOOK_URL != ''
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: "🚀 Backend deployment successful! New version is live at https://${{ secrets.DOMAIN }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on failure
      if: (needs.deploy.result == 'failure' || needs.build.result == 'failure' || needs.test.result == 'failure') && vars.SLACK_WEBHOOK_URL != ''
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: "❌ Backend deployment failed! Check GitHub Actions for details."
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 